# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b7eb3b0dbbebf0548041f3817ecb2f9"
name = "slay-wear"
handle = "slay-wear"
application_url = "https://gel-computed-rc-sphere.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c43919de.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gel-computed-rc-sphere.trycloudflare.com/auth/callback",
  "https://gel-computed-rc-sphere.trycloudflare.com/auth/shopify/callback",
  "https://gel-computed-rc-sphere.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
